#######################################################################################
# Book settings
title                       : '' # The title of the book. Will be placed in the left navbar.
author                      : Open Threat Research @OTR_Community # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : "images/logo/logo.png"  # A path to the book logo
only_build_toc_files        : true # Disable building files that aren’t in the Table of Contents
exclude_patterns            : []  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
description: >- # this means to ignore newlines until "baseurl:"
  The first community Infosec Jupyterthon!

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  announcement: "💖 The InfoSec Jupyterthon is back! December 2nd and 3rd, 2022 🚀"
  favicon                   : "images/logo/favicon.jpg"  # A path to a favicon image
  navbar_number_sections    : false  # Add a number to each section in your left navbar
  navbar_footer_text        : 'Powered by <a href="https://jupyterbook.org">Jupyter Book</a>'  # Will be displayed underneath the left navbar.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true
  use_issues_button         : true
  baseurl                   :  https://infosecjupyterthon.com/
  
#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : "jupyterlab"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebelab                  : true  # Add a thebelab button to pages (requires the repository to run on Binder)

repository:
  url                       : https://github.com/OTRF/infosec-jupyterthon  # The URL to your book's repository
  path_to_book              : "docs"  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings
#######################################################################################

# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

sphinx:
  extra_extensions:
    - sphinx_click.ext
    - sphinx_inline_tabs